# Generated by Django 5.2.7 on 2025-11-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('DIRECTOR', 'Director'), ('INGRESO', 'Personal de Ingreso'), ('ENFERMERA', 'Enfermera'), ('RECEPCIONISTA', 'Recepcionista')], max_length=20),
        ),
    ]
