# Generated by Django 5.2.8 on 2025-11-23 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisitos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_personales', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True)),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='TRATAMIENTO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(blank=True, max_length=100, null=True)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centrosalud.area')),
                ('medico_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones', to='centrosalud.fichamedica')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centrosalud.tratamientomedico')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='centro_salud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrosalud.centrosalud'),
        ),
        migrations.CreateModel(
            name='AtencionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('atencion_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrosalud.atencionmedica')),
                ('examen_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrosalud.examenmedico')),
            ],
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='centrosalud.paciente'),
        ),
    ]
