# Generated by Django 5.2.7 on 2025-11-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrosalud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='estado',
            field=models.CharField(choices=[('EN_ALTA', 'En Alta'), ('EN_TRATAMIENTO', 'En Tratamiento'), ('PRE_OPERATORIO', 'Pre Operatorio'), ('POST_OPERATORIO', 'Post Operatorio')], default='EN_TRATAMIENTO', max_length=20),
        ),
    ]
