# Generated by Django 5.2.7 on 2025-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrosalud', '0002_alter_fichamedica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionmedica',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
