# Generated by Django 5.2.7 on 2025-11-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrosalud', '0003_alter_atencionmedica_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CESFAM', 'Cesfam')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centrosalud.areacategory'),
        ),
    ]
